server:
  port: 8081
spring:
  application:
    name: client-backend
  datasource:
    password: admin
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:25432}/person_database
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
cache:
  type: LFU
  size: 3

validate-token:
  apihost: http://localhost:8081